DROP TABLE IF EXISTS PREFERENCE;
DROP TABLE IF EXISTS CUSTOMER;
DROP INDEX IF EXISTS customerId_PREFERENCEiNDEX;



CREATE TABLE CUSTOMER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  userName VARCHAR(64) NOT NULL,
  name VARCHAR(255) NOT NULL,
  createdBy INT NOT NULL,
  creationTime DATETIME NOT NULL,
  modifiedBy INT NULL,
  modifiedTime DATETIME NULL
);


CREATE TABLE PREFERENCE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  customerId INT NOT NULL,
  preferenceType VARCHAR(25) NOT NULL,
  createdBy INT NOT NULL,
  creationTime DATETIME NOT NULL,
  modifiedBy INT NULL,
  modifiedTime DATETIME NULL,
  FOREIGN KEY (customerId) REFERENCES CUSTOMER(ID)
);
CREATE INDEX customerId_PREFERENCEiNDEX ON PREFERENCE(customerId);


INSERT INTO CUSTOMER(id,userName,name,createdBy,creationTime,modifiedBy,modifiedTime) VALUES(1,'admin','Customer Preference Admin',1,CURRENT_TIMESTAMP(),NULL,NULL)